# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.cache/wt [current_project]
set_property parent.project_path K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo k:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/ALU.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/AR.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/Accumulator.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/CommonBus.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/Computer.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/DR.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/INPR.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/Instruction_Register.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/Interrupt.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/OUTPR.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/PC.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/RAM.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/Secounce_Counter.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/TR.v
  K:/Users/mohammed/Downloads/8_bit_computer/8_bit_computer.srcs/sources_1/new/Computer_tp.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Computer_tp -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Computer_tp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Computer_tp_utilization_synth.rpt -pb Computer_tp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
